# ======== Required ===========

# Or set REDIS_IP or REDIS_PORT_6379_TCP_ADDR environment variable
redisIp: ""

# Or set RETHINKDB_IP or RETHINKDB_PORT_28015_TCP_ADDR environment variable
rethinkdbIp: ""

# ======== Optional ===========

# taskTimeout: 30s
# dockerHost: "unix:///var/run/docker.sock"
# dockerCertPath: "$HOME/.boot2docker/certs/boot2docker-vm"

# Also REDIS_PORT or REDIS_PORT_6379_TCP_PORT
# redisPort: ""

# Also RETHINKDB_PORT or RETHINKDB_PORT_28015_TCP_PORT
# rethinkdbPort: ""
